# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js 12.8
        uses: actions/setup-node@v1
        with:
          node-version: 12.8

      - name: Install
        run: npm install -f

      # - name: Lint
      #   run: ./node_modules/.bin/ng lint

      - name: Build
        run: ./node_modules/.bin/ng build --prod

      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: dist/static

      # - name: Test
      #   run: ./node_modules/.bin/ng test --configuration=ci

  deploy:
      runs-on: ubuntu-18.04
      steps:
        - name: Download
              uses: actions/download-artifact@v1
              with:
                name: build

        - name: Deploy to Pages
          uses: JamesIves/github-pages-deploy-action@releases/v3
          with:
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            BRANCH: gh-pages # The branch the action should deploy to.
            FOLDER: dist/static # The folder the action should deploy.
